### PR TITLE
#185106847 user login with email and password

### PR DESCRIPTION
**Pull request by JENNY-257**
What does this PR do?

This PR is for allowing users to login with email and password

How should this be manually tested?

Installation
1. Clone the repository by running

git clone https://github.com/atlp-rwanda/destructors-ec-fe.git

**2. Navigate to the project directory by running **

cd destructors-ec-fe
ft-login-email-password-185106847

**3. Install the necessary dependencies by running **

npm install
**4. Start the application by run start command **

npm run dev

Navigate to the app url htttp://localhost:/auth/login
Test the form validation by trying to submit the empty form
Fill all the input field as required

Related pivottracker:185106847

Any background context you want to provide?
N/A
Screenshots (if appropriate)

.Figma design

Screenshot 2023-05-18 at 18 38 13

Screenshot 2023-05-18 at 18 43 19

.OutPut

Screenshot 2023-05-18 at 18 48 41

Screenshot 2023-05-18 at 18 56 20

Questions:
none

### CODE REVIEW

**Review by istafrica-dennw — CHANGES_REQUESTED** [review]
Add  2 screenshots: the figma and your solution.

**Comment by ba-lambert** [comment]
@JENNY-257 you can't show your password to any one so try to hide the password

Screenshot 2023-05-22 105702

Also mark this undefined in the post request

**Review by ba-lambert — CHANGES_REQUESTED** [review]
@JENNY-257 you can't show your password to any one so try to hide the password

Screenshot 2023-05-22 105702

Also mark this undefined in the post request

**Review by divinecharlotte — APPROVED** [review]

**Review by divinecharlotte — APPROVED** [review]

**Review by nkurunziza1 — APPROVED** [review]

**Review by mjeanbosco19 — APPROVED** [review]

**Review by katros1 — APPROVED** [review]

**Review by Abdulkeza — APPROVED** [review]
Nice Work

**Pull request merged**
